name: Publish Docker Image

on:
  push:
    branches:
      - main  # Trigger on pushes to the main branch

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write  # Needed to push to GHCR

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and tag the Docker image
        run: |
          OWNER=$(echo "${{ github.repository_owner }}" | tr '[:upper:]' '[:lower:]')
          REPO_NAME=$(echo "${{ github.event.repository.name }}" | tr '[:upper:]' '[:lower:]')
          IMAGE_NAME=ghcr.io/$OWNER/$REPO_NAME
          TAG=${{ github.sha }}
          echo "Building Docker image $IMAGE_NAME with tag $TAG"
          docker build -t $IMAGE_NAME:latest -t $IMAGE_NAME:$TAG .

      - name: Push the Docker image
        run: |
          OWNER=$(echo "${{ github.repository_owner }}" | tr '[:upper:]' '[:lower:]')
          REPO_NAME=$(echo "${{ github.event.repository.name }}" | tr '[:upper:]' '[:lower:]')
          IMAGE_NAME=ghcr.io/$OWNER/$REPO_NAME
          TAG=${{ github.sha }}
          echo "Pushing Docker image $IMAGE_NAME with tags latest and $TAG"
          docker push $IMAGE_NAME:latest
          docker push $IMAGE_NAME:$TAG

      - name: Clean up local images (optional)
        run: docker rmi -f $(docker images -q) || true
